root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main.exe"  # Pastikan ekstensi .exe untuk Windows
  cmd = "go build -o ./tmp/main.exe ./cmd/api/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"

[log]
  time = false

[misc]
  clean_on_exit = true